workspace:
  path: /mirror-tv-nuxt
pipeline:
  startSlack:
    image: plugins/slack
    channel: jenkins
    secrets: [slack_webhook]
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    template: >
      *start* building *{{repo.name}}* <${DRONE_BUILD_LINK}|#{{build.number}}>.
      Someone gave *{{build.branch}}* a little push.
    when:
      event: [push]
      branch: [dev, master]
  
  restoreCache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.yarn-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
    when:
      event: [push]
      branch: [dev, master]
  
  #getDevConfig:
  #  image: gcr.io/mirror-tv-275709/drone-cloud-sdk:latest
  #  secrets: [google_credentials]
  #  commands:
  #  - gcloud source repos clone configs ../configs
  #  - cp ../configs/mirror-tv-nuxt/dev/config.js ./configs/config.js
  #  when:
  #    event: [push]
  #    branch: [dev]
  
  build:
    image: node:12.16.2-slim
    commands:
    - apt-get update && apt-get install -y node-gyp
    - yarn install
    - yarn run build
    when:
      event: [push]
      branch: [dev, master]
  
  publish:
    image: plugins/gcr
    repo: mirror-tv-275709/${DRONE_REPO_NAME}
    tag: ${DRONE_BRANCH}_${DRONE_COMMIT_AUTHOR}_${DRONE_BUILD_NUMBER}
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    secrets: [google_credentials]
    when:
      event: [push]
      branch: [dev, master]
  
  deployDev:
    image: nytimes/drone-gke
    zone: asia-east1-a
    cluster: dev
    namespace: default
    verbose: true
    secrets:
      - source: google_credentials
        target: token
    vars:
      image: gcr.io/mirror-tv-275709/${DRONE_REPO_NAME}:${DRONE_BRANCH}_${DRONE_COMMIT_AUTHOR}_${DRONE_BUILD_NUMBER}
      app: ${DRONE_REPO_NAME}
      tier: frontend
    when:
      event: [push]
      branch: [dev]

  rebuildCache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./.yarn-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
    when:
      branch: [dev, master]
  
  finishSlack:
    image: plugins/slack
    channel: jenkins
    secrets: [slack_webhook]
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    when:
      status: [success, failure]
      event: [push]
      branch: [dev, master]
    template: >
      {{#success build.status}}
        *success* ${DRONE_REPO_NAME}:${DRONE_BRANCH}_${DRONE_COMMIT_AUTHOR}_${DRONE_BUILD_NUMBER} was well served.
        Check out our new <https://www.google.com|mirror-tv-nuxt>.
      {{else}}
        Houston, we have a problem. Build <${DRONE_BUILD_LINK}|#{{build.number}}> failed.
      {{/success}}
  