steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - source
      - repos
      - clone
      - github_mirror-media_kubernetes-configs
      - ./dockerignore/kubernetes-configs
  - name: bash
    args:
      - cp
      - ./dockerignore/kubernetes-configs/mirror-tv-nuxt/overlays/dev/configs/config.js
      - ./configs/config.js
  - name: bash
    args:
      - cp
      - ./dockerignore/kubernetes-configs/mirror-tv-nuxt/overlays/dev/configs/gcskeyfile.json
      - ./gcskeyfile.json
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/${PROJECT_ID}/mirror-tv-nuxt:${BRANCH_NAME}_${SHORT_SHA}'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/mirror-tv-nuxt

  # NOTICE: THE FOLLOWING STEPS ARE FOR TEMPRARY USAGE
  # build `kustomize` configs
  - name: 'launcher.gcr.io/google/ubuntu1604'
    entrypoint: bash
    args:
      - '-c'
      - |
        # install kustomize
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

        # mv kubernetes-configs folder
        mv ./dockerignore/kubernetes-configs /workspace/kubernetes-configs

        # cd to (dev|staging) environment kustimzation root
        cd /workspace/kubernetes-configs/mirror-tv-nuxt/overlays/${BRANCH_NAME}

        # update docker image
        /workspace/kustomize edit set image mirror-tv-nuxt=gcr.io/${PROJECT_ID}/mirror-tv-nuxt:${BRANCH_NAME}_${SHORT_SHA}

        # back to kubernetes-configs root
        cd /workspace/kubernetes-configs

        /workspace/kustomize build "./mirror-tv-nuxt/overlays/${BRANCH_NAME}/" >> $_FILE_TO_DEPLOY
        echo "---" >> $_FILE_TO_DEPLOY

        # print out configs
        cat $_FILE_TO_DEPLOY

  # deploy to kubernetes cluster by config file
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - apply
      - -f
      - $_FILE_TO_DEPLOY
      - --dry-run=server
      - --validate=true
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-east1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=tv-cluster'

timeout: 1200s

substitutions:
  _FILE_TO_DEPLOY: /workspace/config-to-deploy.txt # default value

images:
  - gcr.io/$PROJECT_ID/mirror-tv-nuxt

