query allPublishedPostsByCategoryTitle($categoryTitle: String!) {
  allPostsCategory: allPosts(
    sortBy: publishTime_DESC,
    where: {
      Category_some: {
        title: $categoryTitle
      },
      state: published
    }
  ) {
    id
    title
    slug
    publishTime
    heroImage {
      urlMobileSized
    }
  }
}
