#import "~/apollo/fragments/listingPagePost.gql"

query allPublishedPostsByCategorySlug(
  $categorySlug: String!
  $first: Int = 13
  $skip: Int = 0
  $filteredSlug: [String] = [""],
) {
  allPostsCategory: allPosts(
    sortBy: publishTime_DESC
    where: {
      categories_some: { slug: $categorySlug }
      slug_not_in: $filteredSlug,
      state: published
    }
    first: $first
    skip: $skip
  ) {
    id
    publishTime
    ...listingPagePost
  }

  meta: _allPostsMeta(
    sortBy: publishTime_DESC
    where: {
      categories_some: { slug: $categorySlug }
      slug_not_in: $filteredSlug,
      state: published
    }
  ) {
    count
  }
}
