#import "~/apollo/fragments/listingPagePost.gql"

query allPublishedPosts($first: Int = 12, $skip: Int = 0) {
  allPublishedPosts: allPosts(
    sortBy: publishTime_DESC,
    where: {
      slug_not_in: [
        "privacy",
        "ad-sales",
        "press-self-regulation",
        "webauthorization",
        "biography",
        "complaint",
        "standards",
        "faq",
        "aboutus",
      ]
      state: published
    },
    first: $first,
    skip: $skip
  ) {
    id
    publishTime
    categories {
      name
    }
    ...listingPagePost
  }

  meta: _allPostsMeta(
    sortBy: publishTime_DESC,
    where: {
      state: published
    }
  ) {
    count
  }
}
