query allPublishedPostsByCategorySlug($categorySlug: String!, $first: Int = 13, $skip: Int = 0) {
  allPostsCategory: allPosts(
    sortBy: publishTime_DESC,
    where: {
      categories_some: {
        slug: $categorySlug
      },
      state: published
    },
    first: $first,
    skip: $skip
  ) {
    id
    title
    slug
    publishTime
    heroImage {
      urlMobileSized
    }
  }

  meta: _allPostsMeta(
    sortBy: publishTime_DESC,
    where: {
      categories_some: {
        slug: $categorySlug
      },
      state: published
    }
  ) {
    count
  }
}

query postsByCategorySlug ($category: String, $first: Int = 10, $skip: Int = 0) {
  posts: allPosts(
    sortBy: publishTime_DESC,
    where: {
      categories_some: {
        slug: $category
      },
      state: published
    },
    first: $first,
    skip: $skip
  ) {
    slug
    title
    heroImage {
      urlMobileSized
    }
  }

  meta: _allPostsMeta(where: {
    categories_some: {
      slug: $category
    },
    state: published
  }) {
    count
  }
}
