#import "~/apollo/fragments/listingPagePost.gql"

query allPublishedPostsByCategorySlug(
  $categorySlug: String!,
  $filteredSlug: [String] = [""],
  $withCount: Boolean = false,
  $first: Int = 13,
  $skip: Int = 0,
) {
  allPostsCategory: allPosts(
    sortBy: publishTime_DESC
    where: {
      state: published,
      slug_not_in: $filteredSlug,
      categories_some: {
        slug: $categorySlug
      }
    }
    first: $first
    skip: $skip
  ) {
    id
    publishTime
    ...listingPagePost
  }

  _allPostsMeta(
    where: {
      state: published,
      slug_not_in: $filteredSlug,
      categories_some: {
        slug: $categorySlug
      }
    }
  ) @include(if: $withCount) {
    count
  }
}
