#import "~/apollo/fragments/listingPagePost.gql"

query allPublishedPosts(
  $first: Int = 12,
  $filteredSlug: [String] = [""],
  $skip: Int = 0
) {
  allPublishedPosts: allPosts(
    sortBy: publishTime_DESC,
    where: {
      slug_not_in: $filteredSlug,
      categories_every: {
        slug_not_in: "ombuds"
      },
      state: published
    },
    first: $first,
    skip: $skip
  ) {
    id
    publishTime
    categories {
      slug
      name
    }
    ...listingPagePost
  }

  meta: _allPostsMeta(
    sortBy: publishTime_DESC,
    where: {
      slug_not_in: $filteredSlug,
      categories_every: {
        slug_not_in: "ombuds"
      },
      state: published
    }
  ) {
    count
  }
}
