query fetchAllArtShowsByShowLatest($first: Int, $skip: Int, $slug: String) {
  allArtShows(
    first: $first
    skip: $skip
    where: { series_some: { section_some: { show_some: { slug: $slug } } } }
    sortBy: createdAt_DESC
  ) {
    slug
    name
    heroImage {
      urlMobileSized
      urlOriginal
    }
    heroVideo {
      youtubeUrl
      coverPhoto {
        urlOriginal
        urlMobileSized
      }
      description
      state
    }
    author {
      name
    }
    series {
      name
    }
  }
  _allArtShowsMeta(
    where: { series_some: { section_some: { show_some: { slug: $slug } } } }
  ) {
    count
  }
}

query fetchAllArtShowsByAuthor(
  $authorSlug: String!,
  $showSlug: String!,
  $first: Int,
  $skip: Int
) {
  allArtShows(
    where: {
      author_some: {
        slug: $authorSlug,
      },
      series_some: {
        section_some: {
          show_some: {
            slug: $showSlug,
          },
        },
      },
    },
    first: $first,
    skip: $skip
  ) {
    slug
    name
    heroImage {
      urlMobileSized
      urlOriginal
    }
    heroVideo {
      youtubeUrl
      coverPhoto {
        urlMobileSized
        urlOriginal
      }
      state
    }
  }
  _allArtShowsMeta(
    where: {
      author_some: {
        slug: $authorSlug,
      },
      series_some: {
        section_some: {
          show_some: {
            slug: $showSlug,
          },
        },
      },
    },
  ) {
    count
  }
}

query fetchAllArtShowsBySeries(
  $seriesSlug: String!,
  $first: Int,
  $skip: Int
) {
  allArtShows(
    where: {
      series_some: {
        slug: $seriesSlug,
      },
    },
    first: $first,
    skip: $skip
  ) {
    slug
    name
    heroImage {
      urlMobileSized
      urlOriginal
    }
    heroVideo {
      youtubeUrl
      coverPhoto {
        urlMobileSized
        urlOriginal
      }
      state
    }
  }
  _allArtShowsMeta(
     where: {
      series_some: {
        slug: $seriesSlug,
      },
    },
  ) {
    count
  }
}

query fetchArtShowBySlug(
  $episodeSlug: String!,
) {
  allArtShows(
    where: {
      slug: $episodeSlug
    },
  ) {
    slug
    name
    heroImage {
      urlDesktopSized
      urlOriginal
    }
    heroVideo {
      youtubeUrl
      coverPhoto {
        urlMobileSized
        urlOriginal
      }
    }
    series {
      slug
      name
      section {
        slug
        name
      }
    }
    author {
      slug
      name
      bioApiData
      image {
        urlMobileSized
        urlOriginal
      }
    }
    contentApiData
  }
}
