query fetchContactBySlug($slug: String!) {
  allContacts(
    where: {
      slug: $slug
    }
  ) {
    name
    image {
      urlTabletSized
    }
    facebook
    instatgram
    twitter
    bio
  }
}

query fetchContactByAnchorPerson {
  allContacts(
    where: {
      anchorperson: true
    }
  ) {
    name
    image {
      urlMobileSized
    }
    slug
  }
}

query fetchContactByHosts {
  allContacts(
    where: {
      host: true
    }
  ) {
    name
    image {
      urlMobileSized
    }
    slug
  }
}
