query fetchContactBySlug(
  $slug: String!
) {
  allContacts(
    where: {
      slug: $slug
    }
  ) {
    name
    facebook
    instagram
    twitter
    bioApiData
    showhostImg {
      urlTabletSized
      urlDesktopSized
      urlOriginal
    }
  }
}

query fetchContactsByRole(
  $isAnchorperson: Boolean = false,
  $isHost: Boolean = false,
) {
  allContacts(
    where: {
      anchorperson: $isAnchorperson,
      host: $isHost,
    }
    sortBy: updatedAt_DESC
  ) {
    name
    slug
    anchorImg {
      urlTabletSized
      urlMobileSized
      urlOriginal
    }
  }
}
