query fetchContactBySlug(
  $slug: String!
) {
  allContacts(
    where: {
      slug: $slug
    }
  ) {
    name
    facebook
    instagram
    twitter
    bioApiData
    showhostImg {
      urlTabletSized
      urlDesktopSized
      urlOriginal
    }
  }
}

query fetchContactsByAnchorPerson {
  allContacts(
    where: {
      anchorperson: true,
    }
    sortBy: updatedAt_DESC
  ) {
    name
    slug
    anchorImg {
      urlTabletSized
      urlMobileSized
      urlOriginal
    }
  }
}

query fetchContactsByHost {
  allContacts(
    where: {
      host: true,
    }
    sortBy: updatedAt_DESC
  ) {
    name
    slug
    anchorImg {
      urlTabletSized
      urlMobileSized
      urlOriginal
    }
  }
}
