query fetchEditorChoices(
  $first: Int = 5,
) {
  allEditorChoices(
    where: {
      state: published,
      choice: {
        state: published,
      }
    },
    first: $first,
    sortBy: [sortOrder_ASC,  createdAt_DESC],
  ) {
    choice {
      name
      slug
      style
      heroImage {
        urlMobileSized
      }
      heroVideo {
        coverPhoto {
          urlDesktopSized
          urlOriginal
        }
      }
    }
  }
}
