query fetchEditorChoices {
  allEditorChoices(
    where: {
      state: published,
      choice: {
        state: published,
      }
    },
    sortBy: [sortOrder_ASC,  createdAt_DESC]
    first: 5
  ) {
    choice {
      id
      name
      slug
      style
      heroImage {
        urlMobileSized
      }
      heroVideo {
        coverPhoto {
          urlDesktopSized
          urlOriginal
        }
      }
    }
  }
}
