#import "~/apollo/fragments/listingPagePost.gql"

query fetchPostsAndCountByTagName (
  $tagName: String,
  $maxResults: Int = 12,
  $skip: Int = 0,
  $withCount: Boolean = false,
) {
  allPosts(
    where: {
      state: published,
      tags_some: {
        name: $tagName
      }
    },
    first: $maxResults,
    skip: $skip,
    sortBy: publishTime_DESC,
  ) {
    publishTime
    ...listingPagePost
  }
  _allPostsMeta(
    where: {
      tags_some: {
        name: $tagName
      }
    },
  ) @include(if: $withCount) {
    count
  }
}

query fetchPostsAndCountByAuthorSlug (
  $authorSlug: String,
  $maxResults: Int = 10,
  $skip: Int = 0,
  $withCount: Boolean = false,
) {
  allPosts(
    where: {
      OR: [
        {
          writers_some: {
            slug: $authorSlug
          }
        },
        {
          photographers_some: {
            slug: $authorSlug
          }
        },
        {
          cameraOperators_some: {
            slug: $authorSlug
          }
        },
        {
          designers_some: {
            slug: $authorSlug
          }
        },
        {
          engineers_some: {
            slug: $authorSlug
          }
        },
        {
          vocals_some: {
            slug: $authorSlug
          }
        },
      ]
    },
    sortBy: publishTime_DESC,
    first: $maxResults,
    skip: $skip,
  ) {
    publishTime
    brief
    categories {
      name
    }
    ...listingPagePost
  }
  _allPostsMeta(
    where: {
      OR: [
        {
          writers_some: {
            slug: $authorSlug
          }
        },
        {
          photographers_some: {
            slug: $authorSlug
          }
        },
        {
          cameraOperators_some: {
            slug: $authorSlug
          }
        },
        {
          designers_some: {
            slug: $authorSlug
          }
        },
        {
          engineers_some: {
            slug: $authorSlug
          }
        },
        {
          vocals_some: {
            slug: $authorSlug
          }
        },
      ]
    },
  ) @include(if: $withCount) {
    count
  }
}

query fetchPosts(
  $first: Int = 12,
  $skip: Int = 0,
  $withCount: Boolean = false,
  $withCoverPhoto: Boolean = false,
) {
  allPosts(
    sortBy: publishTime_DESC,
    where: {
      state: published,
      style_not_in: [wide, projects, script, campaign, readr]
    },
    first: $first,
    skip: $skip
  ) {
    id
    publishTime
    categories {
      name
    }
    ...listingPagePost
    heroVideo @include(if: $withCoverPhoto) {
      coverPhoto {
        urlMobileSized
      }
    }
  }

  _allPostsMeta(
    where: {
      state: published,
      style_not_in: [wide, projects, script, campaign, readr]
    }
  ) @include(if: $withCount) {
    count
  }
}
