query fetchPostPublishedBySlug($slug: String!) {
  postPublished: allPosts(where: { slug: $slug }) {
    style
    name
    brief
    briefApiData
    contentApiData
    publishTime
    updatedAt
    source
    heroImage {
      mobile: urlMobileSized
      desktop: urlDesktopSized
    }
    heroVideo {
      youtubeUrl
      coverPhoto {
        tiny: urlTinySized
        mobile: urlMobileSized
        tablet: urlTabletSized
        desktop: urlDesktopSized
        original: urlOriginal
      }
    }
    heroCaption
    categories {
      slug
      name
    }
    writers {
      name
      slug
    }
    photographers {
      name
      slug
    }
    cameraOperators {
      name
      slug
    }
    designers {
      name
      slug
    }
    engineers {
      name
      slug
    }
    vocals {
      name
      slug
    }
    otherbyline
    tags {
      name
    }
    relatedPosts {
      slug
      state
      name
    }
  }
}
