#import "~/apollo/fragments/listingPagePost.gql"

query fetchPostPublishedBySlug($slug: String!) {
  postPublished: allPosts(where: { slug: $slug }) {
    style
    name
    brief
    briefApiData
    contentApiData
    publishTime
    updatedAt
    source
    isAdult
    heroImage {
      tiny: urlTinySized
      mobile: urlMobileSized
      desktop: urlDesktopSized
    }
    heroVideo {
      youtubeUrl
      coverPhoto {
        tiny: urlTinySized
        mobile: urlMobileSized
        tablet: urlTabletSized
        desktop: urlDesktopSized
        original: urlOriginal
      }
    }
    heroCaption
    categories {
      slug
      name
    }
    writers {
      name
      slug
    }
    photographers {
      name
      slug
    }
    cameraOperators {
      name
      slug
    }
    designers {
      name
      slug
    }
    engineers {
      name
      slug
    }
    vocals {
      name
      slug
    }
    otherbyline
    tags {
      name
    }
    relatedPosts {
      slug
      state
      name
    }
  }
}

query allPublishedPosts(
  $first: Int = 12,
  $filteredSlug: [String] = [""],
  $skip: Int = 0
) {
  allPublishedPosts: allPosts(
    sortBy: publishTime_DESC,
    where: {
      slug_not_in: $filteredSlug,
      categories_every: {
        slug_not_in: "ombuds"
      },
      state: published
    },
    first: $first,
    skip: $skip
  ) {
    id
    publishTime
    categories {
      slug
      name
    }
    ...listingPagePost
  }

  meta: _allPostsMeta(
    sortBy: publishTime_DESC,
    where: {
      slug_not_in: $filteredSlug,
      categories_every: {
        slug_not_in: "ombuds"
      },
      state: published
    }
  ) {
    count
  }
}

query allPublishedPostsByCategorySlug(
  $categorySlug: String!,
  $filteredSlug: [String] = [""],
  $withCount: Boolean = false,
  $first: Int = 13,
  $skip: Int = 0,
) {
  allPostsCategory: allPosts(
    sortBy: publishTime_DESC
    where: {
      state: published,
      slug_not_in: $filteredSlug,
      categories_some: {
        slug: $categorySlug
      }
    }
    first: $first
    skip: $skip
  ) {
    id
    publishTime
    ...listingPagePost
  }

  _allPostsMeta(
    where: {
      state: published,
      slug_not_in: $filteredSlug,
      categories_some: {
        slug: $categorySlug
      }
    }
  ) @include(if: $withCount) {
    count
  }
}

query fetchPostsAndCountByTagName (
  $tagName: String,
  $maxResults: Int = 12,
  $skip: Int = 0,
  $withCount: Boolean = false,
  $filteredSlug: [String] = [""],
) {
  allPosts(
    where: {
      state: published,
      slug_not_in: $filteredSlug,
      categories_every: {
        slug_not_in: "ombuds"
      }
      tags_some: {
        name: $tagName
      }
    },
    first: $maxResults,
    skip: $skip,
    sortBy: publishTime_DESC,
  ) {
    publishTime
    ...listingPagePost
  }
  _allPostsMeta(
    where: {
      state: published,
      slug_not_in: $filteredSlug,
      categories_every: {
        slug_not_in: "ombuds"
      }
      tags_some: {
        name: $tagName
      }
    },
  ) @include(if: $withCount) {
    count
  }
}

query fetchPostsByCategorySlug (
  $category: String,
  $first: Int = 10,
  $skip: Int = 0,
  $style: PostStyleType,
  $withCount: Boolean = false,
  $filteredSlug: [String] = [""],
) {
  allPosts(
    sortBy: publishTime_DESC,
    where: {
      categories_some: {
        slug: $category
      },
      state: published,
      slug_not_in: $filteredSlug,
      categories_every: {
        slug_not_in: "ombuds"
      }
      style: $style
    },
    first: $first,
    skip: $skip
  ) {
    ...listingPagePost
  }
  _allPostsMeta(
    where: {
      categories_some: {
        slug: $category
      },
      state: published,
      slug_not_in: $filteredSlug,
      categories_every: {
        slug_not_in: "ombuds"
      }
      style: $style
    },
  ) @include(if: $withCount) {
    count
  }
}

query fetchPosts(
  $first: Int = 12,
  $skip: Int = 0,
  $withCount: Boolean = false,
  $withCoverPhoto: Boolean = false,
  $filteredSlug: [String] = [""],
) {
  allPosts(
    sortBy: publishTime_DESC,
    where: {
      state: published,
      slug_not_in: $filteredSlug,
      categories_every: {
        slug_not_in: "ombuds"
      }
      style_not_in: [wide, projects, script, campaign, readr]
    },
    first: $first,
    skip: $skip
  ) {
    id
    publishTime
    categories {
      slug
      name
    }
    ...listingPagePost
    heroVideo @include(if: $withCoverPhoto) {
      coverPhoto {
        urlMobileSized
      }
    }
  }

  _allPostsMeta(
    where: {
      state: published,
      slug_not_in: $filteredSlug,
      categories_every: {
        slug_not_in: "ombuds"
      }
      style_not_in: [wide, projects, script, campaign, readr]
    }
  ) @include(if: $withCount) {
    count
  }
}
