query fetchPostPublishedBySlug($slug: String!) {
  postPublished: allPosts(
    where: {
      state: published,
      slug: $slug,
    }
  ) {
    style
    title
    brief
    content
    publishTime
    updatedAt
    heroImage {
      mobile: urlMobileSized
      desktop: urlDesktopSized
    }
    heroVideo {
      coverPhoto {
        tiny: urlTinySized
        mobile: urlMobileSized
        tablet: urlTabletSized
        desktop: urlDesktopSized
        original: urlOriginal
      }
    }
    heroCaption
    categories {
      slug
      title
    }
    writers {
      name
      slug
    }
    photographers {
      name
    }
    cameraOperators {
      name
    }
    designers {
      name
    }
    engineers {
     name 
    }
    vocals {
      name
    }
    otherbyline
    tags {
      name
    }
    relatedPosts {
      slug
      title
    }
  }
}
