query fetchPromotionVideos(
  $first: Int = 5,
) {
  allPromotionVideos(
    where: {
      state: published
    },
    first: $first,
    sortBy: [ sortOrder_ASC, updatedAt_DESC ],
  ) {
    ytUrl
  }
}
