query fetchSchedules(
  $where: ScheduleWhereInput = {}
) {
  allSchedules(
    sortBy: [ hour_ASC, minute_ASC ],
    where: $where
  ) {
    id
    name
    hour
    minute
    replay
    showUrl {
      slug
    }
    parentalGuidelines
  }
}
