query fetchSectionByShowSlug($showSlug: String) {
  allSections(where: { show_some: { slug: $showSlug } }, sortBy: id_ASC) {
    name
    slug
    series {
      name
      slug
      introduction
      heroImage {
        urlMobileSized
      }
    }
  }
}
