#import "~/apollo/fragments/listingSeries.gql"

query fetchSectionByShowSlug($showSlug: String) {
  allSections(where: { show_some: { slug: $showSlug } }, sortBy: id_ASC) {
    name
    slug
  }
}

query fetchSectionBySlug($slug: String) {
  allSections(where: { slug: $slug }) {
    name
    slug
    show {
      slug
    }
    series {
      ...listingSeries
    }
  }
}
