query fetchSeriesBySlug($slug: String) {
  allSeries(where: { slug: $slug }) {
    name
    slug
    introductionApiData
    section {
      show {
        slug
      }
    }
    heroImage {
      urlDesktopSized,
      urlMobileSized
    }
  }
}
