query fetchShowBySlug($slug: String!) {
  allShows(where: { slug: $slug }) {
    slug
    name
    bannerImg {
      urlDesktopSized
      urlMobileSized
    }
    picture {
      urlDesktopSized
      urlMobileSized
    }
    hostName {
      slug
      name
      bio
      image {
        urlMobileSized
      }
    }
    introduction
    facebookUrl
    playList01
    playList02
  }
}
query fetchAllShows {
  allShows(sortBy: [sortOrder_ASC, updatedAt_DESC]) {
    slug
    name
    sortOrder
    bannerImg {
      urlDesktopSized
      urlOriginal
    }

    introduction
    facebookUrl
    playList01
  }
}
