query fetchShowBySlug(
  $slug: String!
  $shouldFetchHost: Boolean = false,
  $shouldFetchStaff: Boolean = false,
  $squareHostImg: Boolean = false,
  $rectHostImg: Boolean = false,
) {
  allShows(
    where: {
      slug: $slug
    }
  ) {
    slug
    name
    bannerImg {
      urlDesktopSized
      urlMobileSized
    }
    picture {
      urlDesktopSized
      urlMobileSized
    }
    hostName(sortBy: [sortOrder_ASC, id_DESC]) @include(if: $shouldFetchHost)  {
      slug
      name
      sortOrder
      bioApiData
      showhostImg @include(if: $squareHostImg) {
        urlMobileSized
        urlOriginal
      }
      anchorImg @include(if: $rectHostImg) {
        urlMobileSized
        urlOriginal
      }
    }
    staffName(sortBy: [sortOrder_ASC, id_DESC]) @include(if: $shouldFetchStaff) {
      slug
      name
      sortOrder
      bioApiData
      showhostImg @include(if: $squareHostImg) {
        urlMobileSized
        urlOriginal
      }
      anchorImg @include(if: $rectHostImg) {
        urlMobileSized
        urlOriginal
      }
    }
    introduction
    facebookUrl
    playList01
    playList02
    trailerPlaylist
    isArtShow
  }
}

query fetchShows {
  allShows(sortBy: [sortOrder_ASC, updatedAt_DESC]) {
    slug
    isArtShow
    bannerImg {
      urlDesktopSized
      urlOriginal
    }
  }
}
