query fetchFeaturedTopics(
  $topicFirst: Int = 4,
  $postFirst: Int = 3,
) {
  allTopics(
    where: {
      state: published,
      isFeatured: true
    },
    first: $topicFirst,
    sortBy: [sortOrder_ASC, updatedAt_DESC ]
  ) {
    slug
    name
    heroImage {
      urlMobileSized
      urlOriginal
    }
    post(
      first: $postFirst,
      sortBy: updatedAt_DESC
    ) {
      slug
      name
    }
  }
}
