query fetchVideoByName($name: String!) {
  allVideos(
    where: { name: $name }
  ) {
    youtubeUrl
    url
  }
}

query fetchVideoByCategory($slug: String!) {
  allVideos(
    where: { categories_some: { slug: $slug } }
  ) {
    youtubeUrl
    url
  }
}
