query fetchVideoEditorChoices {
  allVideoEditorChoices (
    where: {
      state: published,
      videoEditor: {
        state: published,
        style: videoNews
      }
    },
    sortBy: order_ASC
  ) {
    videoEditor {
      slug
      name
      style
      heroImage {
        urlMobileSized
      }
      heroVideo {
        coverPhoto {
          urlOriginal
          urlDesktopSized
        }
      }
    }
  }
}
